version: "3.3"
services:

    # Serveur d'application datalizr
    http:
        image: ${BUILD_VAR_HTTP_IMAGE_REGISTRY_URL}/http:${BUILD_VAR_HTTP_IMAGE_VERSION}
        restart: always
        volumes:
            - www:/usr/local/fzoc/www
        networks:
            default:
                aliases:
                    - ${API_DOMAIN}
        depends_on: 
            - fpm
        env_file:
            - .env

    # Serveur PHP-FPM pour l'interprétation des scripts PHP
    fpm:
        image: ${BUILD_VAR_GLOBAL_REGISTRY_URL}/fpm:${BUILD_VAR_GLOBAL_VERSION}
        restart: always
        volumes:
            - www:/usr/local/fzoc/www
        depends_on: 
            - db
        env_file:
            - .env

    # Serveur de base de données
    db:
        image: ${BUILD_VAR_GLOBAL_REGISTRY_URL}/db:${BUILD_VAR_GLOBAL_VERSION}
        restart: always
        volumes: 
            - db_data:/var/lib/mysql
        env_file:
            - .env

# Volumes
volumes:
    http_www:
    db_data:
