#!/bin/sh


mariadb -u root -p"$MARIADB_ROOT_PASSWORD"<<-EOSQL
    
    CREATE USER '$BDD_USERNAME'@'%' IDENTIFIED BY '$BDD_PASSWORD';
    CREATE DATABASE $BDD_NAME;
    GRANT ALL PRIVILEGES ON $BDD_NAME.* TO '$BDD_USERNAME'@'%';
    FLUSH PRIVILEGES;

EOSQL
